/*
 * This file is part of the Valkyrja Application package.
 *
 * Copyright (c) 2016-present Melech Mizrachi
 *
 * Released under the MIT License. See LICENSE.md for details.
 */

import { spawn, spawnSync } from 'node:child_process';
import { readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { ChildProcessWithoutNullStreams } from 'node:child_process';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

/**
 * End-to-end smoke test for the HTTP entry point (`bin/http.ts`).
 *
 * The route decorators (`@Route` / `@RouteHandler`) that `HomeController` carries
 * are TC39 Stage-3 syntax that the application's Vitest transform cannot parse, so
 * the controller can never be imported into a Vitest module. Instead this boots the
 * real entry in a subprocess **under tsx** — the loader the app actually uses — and
 * drives it over HTTP, proving the decorators execute, the generated routing cache
 * resolves the handlers, and every route renders. This is the true runtime proof
 * for the decorator conversion.
 */
const appRoot = fileURLToPath(new URL('../../../../', import.meta.url));
const tsxBin = fileURLToPath(new URL('../../../../node_modules/.bin/tsx', import.meta.url));
const sindriBin = fileURLToPath(new URL('../../../../node_modules/.bin/sindri', import.meta.url));
const port = 34599;
const baseUrl = `http://127.0.0.1:${port}`;

let server: ChildProcessWithoutNullStreams;
let stderr = '';

/**
 * Snapshot a generated-data directory so the suite can restore it afterwards.
 *
 * The generated `App*Data.ts` files are git-ignored build output; regenerating them
 * here must not leave the working tree dirty for a later lint or test run.
 */
const dataDirectory = join(appRoot, 'src/App/Http/Data');

function snapshotDataDirectory(): Map<string, string> {
    return new Map(readdirSync(dataDirectory).map((name) => [name, readFileSync(join(dataDirectory, name), 'utf8')]));
}

function restoreDataDirectory(snapshot: Map<string, string>): void {
    for (const name of readdirSync(dataDirectory)) {
        const original = snapshot.get(name);

        if (original === undefined) {
            // Generated by this suite and absent beforehand — remove it again.
            rmSync(join(dataDirectory, name));

            continue;
        }

        writeFileSync(join(dataDirectory, name), original);
    }
}

let dataSnapshot: Map<string, string>;

async function waitForServer(timeoutMs: number): Promise<void> {
    const deadline = Date.now() + timeoutMs;

    while (Date.now() < deadline) {
        try {
            await fetch(baseUrl + '/');

            return;
        } catch {
            await new Promise((resolve) => setTimeout(resolve, 100));
        }
    }

    throw new Error(`HTTP entry did not start within ${timeoutMs.toString()}ms. stderr:\n${stderr}`);
}

beforeAll(async () => {
    // The application runs on Sindri's generated routing cache; generate it so the
    // entry boots with the real routes rather than the committed empty stubs.
    dataSnapshot = snapshotDataDirectory();

    const generated = spawnSync(process.execPath, [sindriBin, 'generate', 'src/App/Http/Config.ts'], { cwd: appRoot });
    expect(generated.status).toBe(0);

    server = spawn(process.execPath, [tsxBin, 'bin/http.ts'], {
        cwd: appRoot,
        env: { ...process.env, PORT: port.toString() },
    });

    server.stderr.on('data', (chunk: Buffer) => {
        stderr += chunk.toString();
    });

    await waitForServer(20000);
}, 30000);

afterAll(() => {
    server.kill('SIGKILL');
    restoreDataDirectory(dataSnapshot);
});

describe('HttpEntry (e2e, tsx)', () => {
    it('boots and renders the welcome view for GET /', async () => {
        const response = await fetch(baseUrl + '/');

        expect(response.status).toBe(200);
        expect(await response.text()).toContain('Welcome!');
    });

    it('serves the version route for GET, POST and PUT', async () => {
        for (const method of ['GET', 'POST', 'PUT']) {
            const response = await fetch(baseUrl + '/version', { method });

            expect(response.status).toBe(200);
            expect(await response.text()).toBe('1.0.0');
        }
    });

    it('serves the remaining static routes', async () => {
        const text = await fetch(baseUrl + '/text');
        expect(text.status).toBe(200);
        expect(await text.text()).toBe('Hello World!');

        const home = await fetch(baseUrl + '/home');
        expect(home.status).toBe(200);
        expect(await home.text()).toContain('Home');

        const json = await fetch(baseUrl + '/json');
        expect(json.status).toBe(200);
        expect(await json.text()).toContain('Json response example');

        const cached = await fetch(baseUrl + '/cached');
        expect(cached.status).toBe(200);
        expect(await cached.text()).toContain('Welcome!');
    });

    it('did not emit a runtime error while booting', () => {
        expect(stderr).not.toContain('before initialization');
        expect(stderr).not.toContain('Error');
    });
});
